import { describe, it, expect, beforeEach } from 'vitest';
import { parse23andMe, getSNP, hasSNP, getGenotype } from '../parser';
import type { GenotypeMap } from '../types';

// Sample 23andMe file content for testing
const SAMPLE_23ANDME_HEADER = `# This data file generated by 23andMe at: Thu Jan 01 2024 00:00:00
#
# This file contains raw genotype data, including data that is not used in 23andMe reports.
# This data has undergone a general quality review however only a subset of markers have been
# individually validated for accuracy. As such, this data is suitable only for research,
# educational, and informational use and not for medical or other use.
#
# Below is a text version of your data.  Fields are TAB-separated
# Each line corresponds to a single SNP.  For each SNP, we provide its identifier
# (an rsid or an internal id), its location on the reference human genome, and the
# having at that location on each of your two chromosomes.  The two anchromosome
# are arbitrary labeling of your two chromosomes; that is, "Your" chromosome 1 is
# can refer to either the maternally or paternally inherited drop
#
# rsid	chromosome	position	genotype`;

const SAMPLE_DATA_LINES = `rs4477212	1	82154	AA
rs3094315	1	752566	AG
rs4988235	2	136608646	CT
rs1815739	11	66328095	CC
i702862	1	1234567	GG
rs12345	3	9999999	--`;

const VALID_23ANDME_CONTENT = SAMPLE_23ANDME_HEADER + '\n' + SAMPLE_DATA_LINES;

describe('parse23andMe', () => {
	it('should parse valid 23andMe format', () => {
		const result = parse23andMe(VALID_23ANDME_CONTENT);
		expect(result.snpCount).toBeGreaterThan(0);
		expect(result.data).toBeInstanceOf(Map);
	});

	it('should skip comment lines starting with #', () => {
		const content = `# Comment line
# Another comment
rs4477212	1	82154	AA`;
		const result = parse23andMe(content);
		expect(result.snpCount).toBe(1);
	});

	it('should skip empty lines', () => {
		const content = `rs4477212	1	82154	AA

rs3094315	1	752566	AG

`;
		const result = parse23andMe(content);
		expect(result.snpCount).toBe(2);
	});

	it('should handle no-call genotypes (--)', () => {
		const content = `rs4477212	1	82154	AA
rs12345	3	9999999	--
rs3094315	1	752566	AG`;
		const result = parse23andMe(content);
		// Should have 2 SNPs, not 3 (the -- one is skipped)
		expect(result.snpCount).toBe(2);
		expect(result.data.has('rs12345')).toBe(false);
	});

	it('should normalize rsID to lowercase', () => {
		const content = `RS4477212	1	82154	AA
Rs3094315	1	752566	AG`;
		const result = parse23andMe(content);
		expect(result.data.has('rs4477212')).toBe(true);
		expect(result.data.has('rs3094315')).toBe(true);
		expect(result.data.has('RS4477212')).toBe(false);
	});

	it('should normalize genotype to uppercase and sorted', () => {
		const content = `rs4477212	1	82154	ag
rs3094315	1	752566	ga
rs1234567	2	12345	ct`;
		const result = parse23andMe(content);

		// AG (sorted from ag)
		expect(result.data.get('rs4477212')?.genotype).toBe('AG');
		// AG (sorted from ga)
		expect(result.data.get('rs3094315')?.genotype).toBe('AG');
		// CT (sorted from ct)
		expect(result.data.get('rs1234567')?.genotype).toBe('CT');
	});

	it('should handle tab-delimited format', () => {
		const content = `rs4477212\t1\t82154\tAA`;
		const result = parse23andMe(content);
		expect(result.snpCount).toBe(1);
		expect(result.data.get('rs4477212')?.genotype).toBe('AA');
	});

	it('should handle space-delimited fallback', () => {
		const content = `rs4477212 1 82154 AA`;
		const result = parse23andMe(content);
		expect(result.snpCount).toBe(1);
		expect(result.data.get('rs4477212')?.genotype).toBe('AA');
	});

	it('should detect 23andMe header signature', () => {
		const result = parse23andMe(VALID_23ANDME_CONTENT);
		expect(result.format).toBe('23andme');
	});

	it('should return unknown format when no 23andMe signature', () => {
		const content = `rs4477212	1	82154	AA`;
		const result = parse23andMe(content);
		expect(result.format).toBe('unknown');
	});

	it('should return correct snpCount', () => {
		const content = `rs1	1	100	AA
rs2	1	200	AG
rs3	1	300	CC`;
		const result = parse23andMe(content);
		expect(result.snpCount).toBe(3);
		expect(result.data.size).toBe(3);
	});

	it('should collect warnings for invalid positions', () => {
		const content = `rs4477212	1	notanumber	AA
rs3094315	1	752566	AG`;
		const result = parse23andMe(content);
		expect(result.warnings.length).toBeGreaterThan(0);
		expect(result.warnings[0]).toContain('Invalid position');
	});

	it('should handle rsIDs starting with i (internal IDs)', () => {
		const content = `i702862	1	1234567	GG`;
		const result = parse23andMe(content);
		expect(result.snpCount).toBe(1);
		expect(result.data.has('i702862')).toBe(true);
	});

	it('should skip lines with invalid rsID format', () => {
		const content = `notanrsid	1	82154	AA
rs4477212	1	82154	AA`;
		const result = parse23andMe(content);
		expect(result.snpCount).toBe(1);
	});

	describe('debug info', () => {
		it('should collect sample lines', () => {
			const result = parse23andMe(VALID_23ANDME_CONTENT);
			expect(result.debug.sampleLines.length).toBeGreaterThan(0);
			expect(result.debug.sampleLines.length).toBeLessThanOrEqual(5);
		});

		it('should collect sample SNPs', () => {
			const result = parse23andMe(VALID_23ANDME_CONTENT);
			expect(result.debug.sampleSNPs.length).toBeGreaterThan(0);
			expect(result.debug.sampleSNPs.length).toBeLessThanOrEqual(10);
		});

		it('should track target SNP status (rs4988235)', () => {
			const result = parse23andMe(VALID_23ANDME_CONTENT);
			expect(result.debug.targetSNPsStatus['rs4988235']).toBeDefined();
			expect(result.debug.targetSNPsStatus['rs4988235'].found).toBe(true);
			expect(result.debug.targetSNPsStatus['rs4988235'].genotype).toBe('CT');
		});

		it('should report target SNP not found when missing', () => {
			const content = `rs4477212	1	82154	AA`;
			const result = parse23andMe(content);
			expect(result.debug.targetSNPsStatus['rs4988235'].found).toBe(false);
			expect(result.debug.targetSNPsStatus['rs4988235'].genotype).toBeNull();
		});

		it('should count total and skipped lines', () => {
			const result = parse23andMe(VALID_23ANDME_CONTENT);
			expect(result.debug.totalLines).toBeGreaterThan(0);
			expect(result.debug.skippedLines).toBeGreaterThan(0);
		});
	});
});

describe('genotype normalization (via parse23andMe)', () => {
	it('should uppercase genotype', () => {
		const content = `rs123	1	100	aa`;
		const result = parse23andMe(content);
		expect(result.data.get('rs123')?.genotype).toBe('AA');
	});

	it('should sort alleles alphabetically (AG, not GA)', () => {
		const content = `rs123	1	100	ga`;
		const result = parse23andMe(content);
		expect(result.data.get('rs123')?.genotype).toBe('AG');
	});

	it('should handle single nucleotide (A -> AA)', () => {
		const content = `rs123	1	100	A`;
		const result = parse23andMe(content);
		expect(result.data.get('rs123')?.genotype).toBe('AA');
	});
});

describe('getSNP', () => {
	let testMap: GenotypeMap;

	beforeEach(() => {
		const content = `rs4477212	1	82154	AA
rs3094315	1	752566	AG`;
		const result = parse23andMe(content);
		testMap = result.data;
	});

	it('should find SNP by rsID (case insensitive)', () => {
		const snp = getSNP(testMap, 'rs4477212');
		expect(snp).toBeDefined();
		expect(snp?.genotype).toBe('AA');

		const snpUpper = getSNP(testMap, 'RS4477212');
		expect(snpUpper).toBeDefined();
		expect(snpUpper?.genotype).toBe('AA');
	});

	it('should return undefined for missing SNP', () => {
		const snp = getSNP(testMap, 'rs9999999');
		expect(snp).toBeUndefined();
	});
});

describe('hasSNP', () => {
	let testMap: GenotypeMap;

	beforeEach(() => {
		const content = `rs4477212	1	82154	AA`;
		const result = parse23andMe(content);
		testMap = result.data;
	});

	it('should return true for existing SNP', () => {
		expect(hasSNP(testMap, 'rs4477212')).toBe(true);
	});

	it('should return false for missing SNP', () => {
		expect(hasSNP(testMap, 'rs9999999')).toBe(false);
	});

	it('should be case insensitive', () => {
		expect(hasSNP(testMap, 'RS4477212')).toBe(true);
	});
});

describe('getGenotype', () => {
	let testMap: GenotypeMap;

	beforeEach(() => {
		const content = `rs4477212	1	82154	AA
rs3094315	1	752566	AG`;
		const result = parse23andMe(content);
		testMap = result.data;
	});

	it('should return genotype string for found SNP', () => {
		expect(getGenotype(testMap, 'rs4477212')).toBe('AA');
		expect(getGenotype(testMap, 'rs3094315')).toBe('AG');
	});

	it('should return null for missing SNP', () => {
		expect(getGenotype(testMap, 'rs9999999')).toBeNull();
	});

	it('should be case insensitive', () => {
		expect(getGenotype(testMap, 'RS4477212')).toBe('AA');
	});
});
